In [1]:
import pandas as pd
import requests
import time

In [2]:
data_h_add = pd.read_excel('data/전국 병의원 및 약국 현황 2025.12/1.병원정보서비스(2025.12.).xlsx')
data_h_soa = pd.read_excel('data/전국 병의원 및 약국 현황 2025.12/5.의료기관별상세정보서비스_03_진료과목정보 2025.12..xlsx')

In [11]:
df_h_soa = data_h_soa[['요양기관명', '진료과목코드명','과목별 전문의수', '선택진료 의사수']]

In [12]:
df_h_soa

                 요양기관명  진료과목코드명  과목별 전문의수  선택진료 의사수
0           (VOM)봄안과의원       내과         0         0
1           (VOM)봄안과의원       안과         3         0
2            (복지)예사랑병원  정신건강의학과         2         0
3       (사) 경찰공제회 포항의원       내과         0         0
4       (사) 경찰공제회 포항의원       외과         0         0
...                ...      ...       ...       ...
432521          힘플러스병원      피부과         0         0
432522          힘플러스병원    영상의학과         1         0
432523          힘플러스병원    가정의학과         0         0
432524          힙스청담의원      피부과         0         0
432525          힙스청담의원    가정의학과         1         0

[432526 rows x 4 columns]

In [13]:
df_h_add = data_h_add[['요양기관명','종별코드명','시군구코드명', '읍면동', '주소', '좌표(X)', '좌표(Y)']]

In [14]:
df_h_add

,요양기관명,종별코드명,시군구코드명,읍면동,주소,좌표(X),좌표(Y)
0,(VOM)봄안과의원,의원,대구동구,율하동,"대구광역시 동구 안심로 58, 3층 (율하동, 율하메디빌)",128.691894,35.869852
1,(복지)예사랑병원,정신병원,부산서구,아미동2가,"부산광역시 서구 옥천로130번길 38, (아미동2가)",129.013310,35.097325
2,(사) 경찰공제회 포항의원,의원,포항남구,오천읍,"경상북도 포항시 남구 오천읍 냉천로 656, (오천읍)",129.392899,35.942257
3,(사)경찰공제회 강서적성의원,의원,강서구,외발산동,"서울특별시 강서구 남부순환로 171, 강서운전면허시험장만남의광장 적성검사소호 (외발산동)",126.821985,37.549498
4,(사)경찰공제회남부의원,의원,인천남동구,고잔동,"인천광역시 남동구 아암대로 1247, (고잔동)",126.708861,37.384910
...,...,...,...,...,...,...,...
79427,힘찬한의원,한의원,진주시,신안동,"경상남도 진주시 진양호로 284, 2층 (신안동)",128.064558,35.178636
79428,힘찬한의원,한의원,인천서구,당하동,"인천광역시 서구 고산후로95번길 20, 힘찬프라자 2층 201호 (당하동)",126.696749,37.592665
79429,힘플란트치과의원,치과의원,아산시,둔포면,"충청남도 아산시 둔포면 아산밸리중앙로 89, 3층 302호",127.057823,36.923728
79430,힘플러스병원,병원,순천시,조례동,"전라남도 순천시 신월큰길 13, (조례동)",127.519845,34.960448
79431,힙스청담의원,의원,성남분당구,정자동,"경기도 성남시 분당구 성남대로331번길 3-3, 젤존타워III 8층 805호 (정자동)",127.107331,37.365752

In [15]:
df_h_soa = df_h_soa[df_h_soa['진료과목코드명'] == '소아청소년과']

In [19]:
df_marge = pd.merge(df_h_soa, df_h_add, on='요양기관명', how='inner')

In [21]:
df_merge = df_marge[df_marge['과목별 전문의수'] != 0]

In [24]:
df_merge.to_csv('data_cleaning/지역별_소아청소년과전문의수.csv', encoding='utf-8')

In [44]:
df_seuol = pd.read_csv('data_cleaning/서울시_지역아동센터_ 동추가.csv')
df_incheon = pd.read_csv('data_cleaning/인천_지역아동센터_동추가.csv')
df_gi = pd.read_csv('data_cleaning/경기도_지역아동센터현황_동추가.csv')

In [45]:
df_gi = df_gi.rename(columns={'WGS84위도':'Y좌표값', 'WGS84경도':'X좌표값'})

In [ ]:
df_gi = df_gi.drop('소재지지번주소', axis=1)
df_gi = df_gi.rename(columns={'소재지도로명주소':'주소'})
df_gi = df_gi.drop(columns=['시군명', 'Unnamed: 0'])

In [64]:
df_gi.head()

              시설명                            주소       Y좌표값        X좌표값   행정동
0       새꿈터지역아동센터     경기도 고양시 일산동구 산두로 229번길 29  37.674761  126.778352  정발산동
1       맑은샘지역아동센터     경기도 고양시 일산동구 고봉로 658번길 13  37.715616  126.789983   성석동
2        한빛지역아동센터    경기도 고양시 덕양구 행당로 11번길 11 5층  37.620404  126.825960   토당동
3  푸른학교반디교실지역아동센터  경기도 고양시 덕양구 토당로 78번길 7 22 2층  37.623210  126.819300   토당동
4        신성지역아동센터           경기도 고양시 일산동구 일산로 11  37.641440  126.784387   백석동

In [ ]:
df_incheon = df_incheon.drop('군구명', axis=1)
df_incheon = df_incheon.drop('Unnamed: 0', axis=1)

In [65]:
df_incheon.head()

,시설명,주소,X좌표값,Y좌표값,행정동
0,구립 연안지역아동센터,"인천광역시 축항대로86번길 38, 3층(항동7가)",126.604638,37.453556,항동7가
1,구립 월디지역아동센터,"인천광역시 참외전로72번길 25, 3층(전동)",126.628948,37.476825,전동
2,그루터기지역아동센터,"인천광역시 참외전로 13번길 2, 송월아파트상가 제121-1호",126.621251,37.480031,송월동1가
3,금창지역아동센터,인천광역시 금곡로 44(금창동),126.640497,37.473361,금곡동
4,모리아지역아동센터,인천광역시 화수로 3-7,126.636119,37.479916,송현동

In [ ]:
df_seuol = df_seuol.drop(columns=['자치구명', 'Unnamed: 0', '상세주소'])
df_seuol = df_seuol.rename(columns={'기본주소':'주소'})

In [ ]:
df_seuol.head()

            시설명        X좌표값       Y좌표값                    주소    행정동
0      진성지역아동센터  127.086920  37.567220  서울특별시 광진구 용마산로26길 10    중곡동
1      한울지역아동센터  126.899625  37.501158   서울 영등포구 가마산로46가길 10    대림동
2     테스트지역아동센터  126.977675  37.566477     서울특별시 중구 세종대로 110  태평로1가
3     봄이랑지역아동센터  127.095309  37.593789  서울 중랑구 봉우재로58길 16 3층    망우동
4  라이프칠드런지역아동센터  126.821674  37.484108    서울 구로구 연동로13길 7 2층     항동

In [66]:
df_child = pd.concat([df_gi, df_seuol, df_incheon])

In [67]:
df_child.to_csv('data_cleaning/통합지역아동복지센터.csv')