In [2]:
import pandas as pd

In [10]:
df_guck = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='국립도서관')
df_gong = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='공공도서관')
df_pack = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='박물관')
df_mi = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='미술관')
df_sang = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='생활문화센터')
df_munyea = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='문예회관')
df_gibang = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='지방문화원')
df_munhouse = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='문화의집')
df_mungyeon = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='문학관')
df_burock = pd.read_excel('data/2025 전국 문화기반시설 총람.xlsx', sheet_name='(부록)지역문화재단')

In [16]:
df_guck = df_guck.loc[5:,['Unnamed: 1', 'Unnamed: 2' ,'Unnamed: 4', 'Unnamed: 5']]

In [20]:
df_gong = df_gong.loc[5:,['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 4', 'Unnamed: 5']]

In [25]:
df_pack = df_pack.loc[8:,['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 5', 'Unnamed: 6']]

In [32]:
df_mi = df_mi.loc[8:,['Unnamed: 1','Unnamed: 2','Unnamed: 5','Unnamed: 6']]

In [35]:
df_sang = df_sang.loc[4:,['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 8']]

In [38]:
df_munyea = df_munyea.loc[4:,['Unnamed: 1', 'Unnamed: 2' ,'Unnamed: 4', 'Unnamed: 5']]

In [40]:
df_gibang = df_gibang.loc[4:,['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 6']]

In [43]:
df_munhouse = df_munhouse.loc[5:,['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4']]

In [47]:
df_mungyeon = df_mungyeon.loc[7:,['Unnamed: 1','Unnamed: 2','Unnamed: 9','Unnamed: 10']]

In [49]:
df_burock=df_burock.loc[4:,['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4']]

In [123]:
df_guck

  Unnamed: 1 Unnamed: 2 Unnamed: 4                  Unnamed: 5   법정동   행정동
5         서울        서초구    국립중앙도서관    서울특별시 서초구 반포대로 201 (반포동)   반포동  반포4동
6         서울       영등포구      국회도서관   서울특별시 영등포구 의사당대로 1 (여의도동)  여의도동   여의동
7         서울        서초구   국립장애인도서관    서울특별시 서초구 반포대로 201 (반포동)   반포동  반포4동
8         경기        고양시      법원도서관  경기도 고양시 일산동구 호수로 550 (장항동)   장항동  장항2동

In [114]:
df_gong

,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5
5,서울,강남구,서울특별시교육청강남도서관,서울특별시 강남구 선릉로116길 45 (삼성동) 서울특별시교육청강남도서관
6,서울,강남구,서울특별시교육청개포도서관,서울특별시 강남구 선릉로4길 30 (개포동) 서울특별시교육청 개포도서관
7,서울,강동구,서울특별시교육청강동도서관,서울특별시 강동구 양재대로116길 57 (길동) 강동도서관
8,서울,강동구,서울특별시교육청고덕평생학습관(도서관),서울특별시 강동구 고덕로 295 (고덕동) 고덕평생학습관
9,서울,강서구,서울특별시교육청강서도서관,서울특별시 강서구 등촌로51나길 29 (등촌동) 강서도서관
...,...,...,...,...
1357,제주,제주시,제주시기적의도서관,제주특별자치도 제주시 동광로12길 19 (이도이동) 제주시기적의도서관
1358,제주,제주시,제주꿈바당어린이도서관,제주특별자치도 제주시 연오로 140 (연동) 제주특별자치도 제주시 연오로 140
1359,NaN,NaN,16,NaN
1360,NaN,NaN,22,NaN
1361,NaN,NaN,1296,NaN

In [126]:
cities = ['성남', '고양', '부천', '광명', '하남', '남양주', '용인', '김포', '구리', '안양']

def filter_region(df, cities, col_region='Unnamed: 1', col_city='Unnamed: 2'):
    return df[
        (df[col_region].str.contains('서울|인천', na=False)) |
        (
            (df[col_region].str.contains('경기', na=False)) &
            (df[col_city].str.contains('|'.join(cities), na=False))
        )
    ]

In [ ]:
munhaw = [df_guck, df_gong, df_pack, df_mi, df_sang, df_munyea, df_gibang, df_munhouse, df_mungyeon, df_burock]

In [131]:
munhaw = {
    'guck': df_guck,
    'gong': df_gong,
    'pack': df_pack,
    'mi': df_mi,
    'sang': df_sang,
    'munyea': df_munyea,
    'gibang': df_gibang,
    'munhouse': df_munhouse,
    'mungyeon': df_mungyeon,
    'burock': df_burock
}

munhaw_filtered = {}

for name, df in munhaw.items():
    munhaw_filtered[name + '_c'] = filter_region(df, cities)

In [95]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_address(address):
    try:
        params = {'query' : address}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()
        law_dong = a['documents'][0]['address']['region_3depth_name']   # 법정동
        hang_dong = a['documents'][0]['address']['region_3depth_h_name']   # 행정동
        return pd.Series([law_dong, hang_dong])
        
    except Exception as e:
        print(f"주소 변환 실패: {address} / 에러: {e}")
        return pd.Series([None, None])

In [ ]:
for i in munhaw_filtered.keys():
    munhaw_filtered[i][['법정동', '행정동']] = munhaw_filtered[i].apply(get_address)

In [150]:
for key, df in munhaw_filtered.items():
    addr_col = df.columns[3]   # 3번째 컬럼
    
    df[['법정동', '행정동']] = df[addr_col].apply(get_address)

주소 변환 실패: 서울특별시 송파구 오금로1 (신천동) 신천빗물펌프장 4~5층 / 에러: list index out of range
주소 변환 실패: 경기도 고양시 덕양구 호국로790번길 87 (성사동) 원당도서관 / 에러: list index out of range
주소 변환 실패: 경기도 광명시 소하일로 7 (소하동) 경기도 광명시 소하일로 7 소하도서관 / 에러: list index out of range
주소 변환 실패: 경기도 광명시 철산로 56 (철산동) 경기도 광명시 철산로56 광명시철산도서관 / 에러: list index out of range
주소 변환 실패: 경기도 구리시 갈매중앙로 80 (갈매동) 4~6층 / 에러: list index out of range
주소 변환 실패: 경기도 남양주시 와부읍 월문천로 43  경기도 남양주시 와부읍 월문천로 43 와부도서관 / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)

주소 변환 실패: 서울특별시 노원구 화랑로 574 / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: 서울특별시 성동구 왕십리로 27 / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: 서울특별시 마포구 와우산로 95 홍익대학교 문헌관 3층 / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: 인천광역시 강화군 하점면 강화대로 992-19 / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: 인천광역시 미추홀구 인하로 100 1-013 / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)

주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range
주소 변환 실패: nan / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)

주소 변환 실패: 서울특별시 금천구 가산로 133 / 에러: list index out of range
주소 변환 실패: 인천광역시 연수구 청학동 507, 연수동 651 경계 연수고가차도 지하보도 / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)

주소 변환 실패: 인천광역시 중구 축항대로896번길 81 / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)

주소 변환 실패: 광주광역시 중구 신포로 15번길 76 / 에러: list index out of range
주소 변환 실패: 서울특별시 강남구 테헤란로82길 15, 7~9층 / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)
C:\Users\asia\AppData\Local\Temp\ipykernel_5128\3871427529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['법정동', '행정동']] = df[addr_col].apply(get_address)

In [155]:
new_cols = ['시도', '시군구', '이름', '주소', '법정동', '행정동']

for key, df in munhaw_filtered.items():
    df.columns = new_cols

In [156]:
munhaw_filtered

{'guck_c':    시도   시군구        이름                          주소   법정동   행정동
 5  서울   서초구   국립중앙도서관    서울특별시 서초구 반포대로 201 (반포동)   반포동  반포4동
 6  서울  영등포구     국회도서관   서울특별시 영등포구 의사당대로 1 (여의도동)  여의도동   여의동
 7  서울   서초구  국립장애인도서관    서울특별시 서초구 반포대로 201 (반포동)   반포동  반포4동
 8  경기   고양시     법원도서관  경기도 고양시 일산동구 호수로 550 (장항동)   장항동  장항2동,
 'gong_c':      시도  시군구                    이름                                        주소  \
 5    서울  강남구         서울특별시교육청강남도서관  서울특별시 강남구 선릉로116길 45 (삼성동) 서울특별시교육청강남도서관
 6    서울  강남구         서울특별시교육청개포도서관   서울특별시 강남구 선릉로4길 30 (개포동) 서울특별시교육청 개포도서관
 7    서울  강동구         서울특별시교육청강동도서관          서울특별시 강동구 양재대로116길 57 (길동) 강동도서관
 8    서울  강동구  서울특별시교육청고덕평생학습관(도서관)           서울특별시 강동구 고덕로 295 (고덕동) 고덕평생학습관
 9    서울  강서구         서울특별시교육청강서도서관          서울특별시 강서구 등촌로51나길 29 (등촌동) 강서도서관
 ..   ..  ...                   ...                                       ...
 796  경기  하남시              하남시위례도서관               경기도 하남시 위례대로 230(학암동) 위례도서관
 797  경기  하남시              하남시일가도서관          경기도 하남시 미사강변남로 10 (풍산동) 하남시일가도서관
 798  경기  하남시             하남시 나룰도서관          경기도 하남시 덕풍북로 180 (덕풍동) 하남시 나룰도서관
 799  경기  하남시             하남시 덕풍도서관                경기도 하남시 역말로 14 (덕풍동) 덕풍도서관
 800  경기  하남시             하남시디지털도서관     경기도 하남시 미사강변한강로 290-2 (망월동) 하남시디지털도서관

      법정동   행정동
 5    삼성동  삼성2동
 6    개포동  개포2동
 7     길동    길동
 8    고덕동  고덕2동
 9    등촌동  등촌2동
 ..   ...   ...
 796  학암동   위례동
 797  풍산동  미사3동
 798  덕풍동  덕풍3동
 799  덕풍동  덕풍1동
 800  망월동  미사1동

 [395 rows x 6 columns],
 'pack_c':      시도  시군구               이름                     주소    법정동          행정동
 8    서울  용산구          국립중앙박물관     서울특별시 용산구 서빙고로 137  용산동6가         한강로동
 9    서울  종로구          국립민속박물관       서울특별시 종로구 삼청로 37    세종로        청운효자동
 11   서울  종로구        대한민국역사박물관     서울특별시 종로구 세종대로 198    세종로  종로1.2.3.4가동
 12   서울  용산구          국립한글박물관     서울특별시 용산구 서빙고로 139  용산동6가         서빙고동
 13   서울  서초구      국립국악원 국악박물관   서울특별시 서초구 남부순환로 2364    서초동         서초3동
 ..   ..  ...              ...                    ...    ...          ...
 444  경기  용인시         명지대학교박물관    경기도 용인시 처인구 명지로 116     남동          중앙동
 446  경기  성남시      신구대학교 우촌박물관    경기도 성남시 중원구 광명로 377    금광동         금광2동
 448  경기  용인시         용인대학교박물관  경기도 용인시 처인구 용인대학로 134    삼가동          삼가동
 450  경기  고양시  한국항공대학교 항공우주박물관   경기도 고양시 덕양구 항공대학로 76    화전동          대덕동
 452  경기  성남시    을지대학교 범석의학박물관   경기도 성남시 수정구 산성대로 553    양지동          양지동

 [230 rows x 6 columns],
 'mi_c':      시도   시군구                     이름                         주소      법정동   행정동
 9    서울   종로구           국립현대미술관(서울관)           서울특별시 종로구 삼청로 30      소격동   삼청동
 10   서울    중구          국립현대미술관(덕수궁관)           서울특별시 중구 세종대로 99       정동   소공동
 13   서울   NaN                    NaN                        NaN     None  None
 14   서울    중구              DDP디자인뮤지엄           서울특별시 중구 을지로 281    을지로7가   광희동
 15   서울   강서구                겸재정선미술관       서울특별시 강서구 양천로 47길 36      마곡동  가양1동
 ..   ..   ...                    ...                        ...      ...   ...
 181  경기  남양주시                  한강뮤지엄  경기도 남양주시 와부읍 경강로 926번길 30  와부읍 팔당리   와부읍
 182  경기   용인시                  한국미술관      경기도 용인시 기흥구 마북로 244-2      마북동   마북동
 185  경기   성남시         현대어린이책미술관 MOKA  경기도 성남시 분당구 판교역로 146번길 20      백현동   백현동
 186  경기  남양주시  현대어린이책미술관 MOKA GARDEN          경기도 남양주시 다산순환로 50      다산동  다산1동
 191  경기   성남시            갤러리 우촌(미술관)   경기도 성남시 수정구 적푸리로 9 (상적동)      상적동   고등동

 [79 rows x 6 columns],
 'sang_c':         시도   시군구               이름  \
 4    서울특별시   마포구      서울생활문화센터 서교
 5    서울특별시   금천구         가산생활문화센터
 6    서울특별시   은평구     은평생활문화센터 모여락
 7    서울특별시   종로구      서울생활문화센터 체부
 8    서울특별시  서대문구     천연어울림 생활문화센터
 9    서울특별시   용산구          용산역사박물관
 10   서울특별시   종로구      서울생활문화센터 낙원
 11   서울특별시   구로구     서울생활문화센터 신도림
 12   서울특별시   도봉구              숲속애
 13   서울특별시   중랑구         중랑생활문화센터
 14   서울특별시   성북구          동네마당 뜰안
 15   서울특별시   성동구       서울숲 생활문화센터
 16   서울특별시   성동구     소월아트홀 생활문화센터
 17   서울특별시   광진구        광진구평생학습센터
 18   서울특별시   광진구     돌곶이 생활예술문화센터
 19   서울특별시   양천구         양천생활문화센터
 20   서울특별시   금천구          금천평생학습관
 21   서울특별시   송파구       잠실생활문화지원센터
 22   서울특별시   금천구      금천마을활력소 어울샘
 56   인천광역시   계양구           계양문화회관
 57   인천광역시  미추홀구     학산 생활문화센터 마당
 58   인천광역시    동구       솔마루 생활문화센터
 59   인천광역시   부평구   부평생활문화센터 공감168
 60   인천광역시   연수구   507문화벙커 생활문화센터
 61   인천광역시   연수구       진달래 생활문화센터
 62   인천광역시   옹진군       자월면 생활문화센터
 63   인천광역시   옹진군       북도면 생활문화센터
 64   인천광역시    중구  개항장 문화마당 생활문화센터
 65   인천광역시    서구         가정생활문화센터
 66   인천광역시   남동구         남동생활문화센터
 94     경기도   김포시         월곶생활문화센터
 96     경기도   부천시         오정생활문화센터
 97     경기도   부천시         소사생활문화센터
 98     경기도   성남시  성남서현문화의집 생활문화센터
 101    경기도   용인시       보정역 생활문화센터
 106    경기도   고양시   고양생활문화센터(아람마당)
 107    경기도   고양시  고양생활문화센터(어울림마당)
 108    경기도   고양시   고양생활문화센터(호수마당)
 109    경기도   하남시        생활문화센터 하다

                                               주소      법정동          행정동
 4                        서울특별시 마포구 양화로72, 지하1~2층      서교동          서교동
 5                              서울특별시 금천구 가산로 133     None         None
 6                         서울특별시 은평구 연서로29길 11-10      갈현동         갈현2동
 7                              서울특별시 자하문로1나길 3-2      체부동          사직동
 8                             서울특별시 서대문구 천연동 278      영천동          천연동
 9                        서울특별시 용산구 한강대로14길 35-29    한강로3가         한강로동
 10                            서울특별시 종로구 삼일대로 428      낙원동  종로1.2.3.4가동
 11                    서울특별시 구로구 새말로 117-21, 지하1층     신도림동         신도림동
 12                             서울특별시 도봉구 방학동 518      방학동         방학3동
 13                           서울특별시 중랑구 공릉로2길 8-4       묵동          묵1동
 14                       서울특별시 성북구 동소문로23길 16-27    동선동4가          동선동
 15                      서울특별시 성동구 왕십리로11길 19, 4층    성수동1가       성수1가2동
 16                            서울특별시 성동구 왕십리로 281      행당동         행당1동
 17                          서울특별시 광진구 자양로 15길 60      자양동         자양1동
 18                        서울특별시 성북구 화랑로32길 100-1      석관동          석관동
 19             서울특별시 양천구 목동서로 367 양천문화회관 별관 3~4층      신정동         신정6동
 20                          서울특별시 금천구 범안로 1240-7      독산동         독산2동
 21                            서울특별시 송파구 송파대로 521      잠실동         잠실3동
 22                               서울특별시 금천구 탑골로22      시흥동         시흥5동
 56                         인천광역시 계양구 계양산로35번길 11      계산동         계산2동
 57                            인천광역시 미추홀구 인하로 126      용현동       용현1.4동
 58                     인천광역시 동구 화도진로44번길 18(송현동)      송현동       송현1.2동
 59                           인천광역시 부평구 아트센터로 168      십정동         부평3동
 60     인천광역시 연수구 청학동 507, 연수동 651 경계 연수고가차도 지하보도     None         None
 61              인천광역시 연수구 청학동 507번지 청학중학교 앞 지하보도      청학동          청학동
 62                        인천광역시 옹진군 자월면 자월리 1024  자월면 자월리          자월면
 63                  인천광역시 옹진군 북도면 시도로 61번길  65-4  북도면 시도리          북도면
 64                           인천광역시 중구 신포로 46번길 5       내동         동인천동
 65                              인천광역시 서구 서달로 190      가정동         가정3동
 66                         인천광역시 남동구 독점로 30번길 15      구월동         구월1동
 94                      경기도 김포시 월곶면 군하로 276번길 20  월곶면 군하리          월곶면
 96                    경기도 부천시 성오로172 오정아트홀 지하1층       오정동          오정동
 97                      경기도 부천시 경인옛로73 소사구청 지하1층     소사본동         소사본동
 98                      경기도 성남시 분당구 중앙공원로39번길 29      서현동         서현1동
 101                        경기도 용인시 기흥구 용구대로 2585      보정동          보정동
 106    경기도 고양시 일산동구 중앙로 1286, 고양아람누리 내 아람마슬 지하1층      마두동         마두1동
 107  경기도 고양시 덕양구 어울림로 33, 고양어울림누리 내 높빛언덕마루 지하 2층      성사동         성사2동
 108                 경기도 고양시 일산동구 호수로 595, 호수공원 내      장항동         장항2동
 109                              경기도 신장동 538 외 1      신장동         신장2동  ,
 'munyea_c':         시도  시군구         이름                      주소   법정동    행정동
 4    서울특별시  강남구     강남구민회관       서울특별시 강남구 삼성로 154   대치동   대치2동
 5    서울특별시  강동구     강동아트센터        서울특별시 강동구 동남로870   상일동   상일1동
 6    서울특별시  강북구   강북문화예술회관        서울특별시 강북구 삼각산로85   수유동    인수동
 7    서울특별시  강서구     강서구민회관        서울특별시 강서구 우장산로66  내발산동   우장산동
 8    서울특별시  관악구      관악아트홀     서울특별시 관악구 신림로 3길 35   신림동    대학동
 ..     ...  ...        ...                     ...   ...    ...
 123    경기도  용인시      큰어울마당  경기도 용인시 수지구 문정로 7번길 15  풍덕천동  풍덕천2동
 124    경기도  용인시  문화예술원 마루홀   경기도 용인시 처인구 중부대로 1199   삼가동    삼가동
 125    경기도  용인시      경기국악원     경기도 용인시 기흥구 민속촌로 89   보라동    보라동
 136    경기도  하남시     하남문화재단     경기도 하남시 신평로125(덕풍동)   덕풍동   덕풍3동
 137    경기도  김포시      김포아트홀          경기도 김포시 돌문로 26   사우동    사우동

 [61 rows x 6 columns],
 'gibang_c':      시도      시군구        이름                                         주소  \
 4    서울      종로구     종로문화원                            서울특별시 종로구 율곡로 5
 5    서울       중구     중구문화원             서울특별시 중구 퇴계로50길 59 장충문화체육센터 4층
 6    서울      용산구     용산문화원                       서울특별시 용산구 효창원로 8길 28
 7    서울      성동구     성동문화원         서울특별시 성동구 왕십리로 281 성동문화회관 2층 성동문화원
 8    서울      광진구     광진문화원                      서울특별시 광진구 광나루로 56길 67
 9    서울     동대문구    동대문문화원      서울특별시 동대문구 왕산로 128, 지하2층(용신동, 동의보감타워)
 10   서울      중랑구     중랑문화원         서울특별시 중랑구 면목로 238, 3층(면목동, 중랑구민회관)
 11   서울      성북구     성북문화원                       서울특별시 성북구 성북로4길 13-8
 12   서울      강북구     강북문화원          서울특별시 강북구 삼각산로 85, 강북문화예술회관 본관 3층
 13   서울      도봉구     도봉문화원              서울특별시 도봉구 도봉로 552(창동, 도봉구민회관)
 14   서울      노원구     노원문화원                 서울특별시 노원구 동일로 197길 24(공릉동)
 15   서울      은평구     은평문화원                          서울특별시 은평구 수색로 282
 16   서울     서대문구    서대문문화원              서울특별시 서대문구 백련사길 39 서대문문화회관 2층
 17   서울      마포구     마포문화원                          서울특별시 마포구 백범로 227
 18   서울      양천구     양천문화원             서울특별시 양천구 목동남로 106 갈산문화예술센터 2층
 19   서울      강서구     강서문화원                 서울특별시 강서구 가로공원로 195, 강서문화원
 20   서울      구로구     구로문화원      서울특별시 구로구 경인로 20가길 38, 2층(오류동,오류문화센터)
 21   서울      금천구     금천문화원                      서울특별시 금천구 시흥대로 38길 61
 22   서울     영등포구    영등포문화원                         서울특별시 영등포구 신길로 275
 23   서울      동작구     동작문화원  서울특별시 동작구 장승배기로 10길 42, 3층(상도동, 동작문화복지센터)
 24   서울      관악구     관악문화원                    서울특별시 관악구 신림로3길 35(신림동)
 25   서울      서초구     서초문화원             서울특별시 서초구 강남대로 201 서초문화예술회관 2층
 26   서울      강남구     강남문화원                    서울특별시 강남구 논현로131길40, 1층
 27   서울      송파구     송파문화원                          서울특별시 송파구 올림픽로 44
 28   서울      강동구     강동문화원                서울특별시 강동구 상암로168(강동구민회관 2층)
 57   인천       중구     중구문화원        인천광역시 중구 축항대로 296번길 81 인천중구문화회관내 1층
 58   인천  동구(화도진)    화도진문화원          인천광역시 동구 솔빛로22번길 2 송현1·2동 복합청사 6층
 59   인천     미추홀구  미추홀학산문화원               인천광역시 미추홀구 인하로 126(용현동 81-8)
 60   인천      연수구     연수문화원                  인천광역시 연수구 비류대로 299 청학문화센터
 61   인천      남동구     남동문화원                   인천광역시 남동구 아암대로 1437번길 32
 62   인천      부평구     부평문화원                          인천광역시 부평구 굴포로 151
 63   인천      계양구     계양문화원                  인천광역시 계양구 계산새로 88 6층 609호
 64   인천       서구     서구문화원            인천광역시 서구 염곡로 464번길 15, 쓰리엠타워 7층
 65   인천      강화군     강화문화원                       인천광역시 강화군 강화읍 남문로 52
 66   인천      옹진군     옹진문화원                      인천광역시 중구 서해대로 374(4층)
 89   경기      성남시     성남문화원                   경기도 성남시 수정구 산성대로 215번길 7
 91   경기      안양시     안양문화원          경기도 용인시 처인구 중부대로 1199 용인시문화예술원 1층
 92   경기      부천시     부천문화원                     경기도 부천시 경인로 92번길 33 4층
 93   경기      광명시     광명문화원                    경기도 안산시 상록구 석호로 144(사동)
 97   경기      고양시     고양문화원               경기도 평택시 중앙로 277(남부문화예술회관 1층)
 99   경기      구리시     구리문화원           경기도 시흥시 연성로 13번길 3 조은프라자 4층(하중동)
 100  경기     남양주시    남양주문화원          경기도 파주시 와석순환로 415(운정행복센터, 행정동 2층)
 105  경기      하남시     하남문화원               경기도 이천시 남천로 31, 중리동행정복지센터 2층
 106  경기      용인시     용인문화원                        경기도 양주시 삼일로 29번길 20
 110  경기      김포시     김포문화원                         경기도 포천시 중앙로 34번길 8

          법정동          행정동
 4        사간동  종로1.2.3.4가동
 5      장충동2가          장충동
 6      원효로4가        원효로2동
 7        행당동         행당1동
 8        구의동         구의3동
 9        용두동          용두동
 10       면목동         면목4동
 11    동소문동1가          성북동
 12       수유동          인수동
 13        창동          창5동
 14       공릉동         공릉1동
 15       수색동          수색동
 16       홍은동         홍은2동
 17      신공덕동          공덕동
 18       신정동         신정7동
 19       화곡동         화곡1동
 20       오류동         오류1동
 21       시흥동         시흥3동
 22      영등포동        영등포본동
 23       상도동         상도2동
 24       신림동          대학동
 25       양재동         양재1동
 26       논현동         논현1동
 27       잠실동         잠실7동
 28       천호동         천호1동
 57     신흥동3가          신흥동
 58       송현동       송현1.2동
 59       용현동       용현1.4동
 60       청학동          청학동
 61       논현동        논현고잔동
 62       삼산동         삼산2동
 63       계산동         계산4동
 64       가정동         가정1동
 65   강화읍 남산리          강화읍
 66     신흥동3가          신흥동
 89       신흥동         신흥1동
 91       삼가동          삼가동
 92       송내동         송내2동
 93        사동           사동
 97       비전동         비전2동
 99       하중동          연성동
 100      와동동         운정1동
 105      중리동          중리동
 106  광적면 가납리          광적면
 110      신읍동          포천동  ,
 'munhouse_c':        시도   시군구           이름                             주소      법정동   행정동
 5   서울특별시   은평구     응암1동문화의집             서울특별시 은평구 백련산로 179      응암동  응암1동
 6   서울특별시   노원구       노원문화의집  서울특별시 노원구 동일로 1530-1 마들역 지하1층      상계동  상계8동
 7   서울특별시   성북구  김중업 건축 문화의집           서울특별시 성북구 장위로21나길 11      장위동  장위1동
 8   서울특별시   강동구         민속의집            서울특별시 강동구 고덕로83길 55      고덕동  고덕2동
 15    경기도   성남시       성남문화의집        경기도 성남시 수정구 산성대로215번길 7      신흥동  신흥1동
 16    경기도  남양주시     남양주시문화의집   경기도 남양주시 진접읍 금강로 1509-26(3층)  진접읍 장현리   진접읍
 20    경기도   고양시       고양문화의집            경기도 고양시 일산서구 산현로 99      탄현동  탄현1동,
 'mungyeon_c':     시도  시군구       이름                    주소   법정동   행정동
 12  인천   중구  한국근대문학관  광주광역시 중구 신포로 15번길 76  None  None
 14  경기  광명시   기형도문학관       경기도 광명시 오리로 268   일직동  소하2동,
 'burock_c':        시도   시군구        이름                                        주소    법정동  \
 4   서울특별시  동대문구    서울문화재단                       서울특별시 동대문구 청계천로 517    용두동
 6   인천광역시    중구    인천문화재단                         인천광역시 중구 제물량로 195   항동5가
 22  서울특별시   노원구    노원문화재단               서울특별시 노원구 중계로 181, 노원문화예술회관    중계동
 23  서울특별시   성북구    성북문화재단                       서울특별시 성북구 아리랑로12길 4    돈암동
 24  서울특별시   종로구    종로문화재단                         서울특별시 종로구 새문안로 41  신문로2가
 25  서울특별시   은평구    은평문화재단                     서울특별시 은평구 녹번로 16(녹번동)    녹번동
 26  서울특별시   성동구    성동문화재단                      서울특별시 성동구 고산자로 10길 9    행당동
 27  서울특별시   광진구    광진문화재단         서울특별시 광진구 능동로 76, 4층(자양동, 나루아트센터)    자양동
 28  서울특별시   강동구    강동문화재단                         서울특별시 강동구 동남로 870    상일동
 29  서울특별시   강남구    강남문화재단                서울특별시 강남구 테헤란로82길 15, 7~9층   None
 30  서울특별시   서초구    서초문화재단                          서울특별시 서초구 사평대로55    반포동
 31  서울특별시   동작구    동작문화재단                      서울특별시 동작구 성대로 25가길 8    상도동
 32  서울특별시   양천구    양천문화재단          서울특별시 양천구 목동서로 367, 양천문화회관 별관 5층    신정동
 33  서울특별시   구로구    구로문화재단                    서울특별시 구로구 가마산로25길 9-24    구로동
 34  서울특별시   금천구    금천문화재단                서울특별시 금천구 금하로 643, 3층 / 6층    시흥동
 35  서울특별시   관악구    관악문화재단                   서울특별시 관악구 신림로3길 35(신림동)    신림동
 36  서울특별시    중구  서울중구문화재단                          서울특별시 중구 퇴계로 387    흥인동
 37  서울특별시   마포구    마포문화재단                       서울특별시 마포구 대흥로20길 28    대흥동
 38  서울특별시  영등포구   영등포문화재단                서울특별시 영등포구 국회대로 596(당산동3가)  당산동3가
 39  서울특별시   강북구    강북문화재단                     서울특별시 강북구 삼각산로 85, 3층    수유동
 40  서울특별시   도봉구    도봉문화재단  서울특별시 도봉구 노해로63길 43, 302호(도봉구행정지원센터, 창동)     창동
 41  서울특별시  동대문구   동대문문화재단                      서울특별시 동대문구 무학로44길 38    제기동
 42  서울특별시   송파구    송파문화재단              서울특별시 송파구 백제고분로 242(삼전동), 2층    삼전동
 43  서울특별시   중랑구    중랑문화재단    서울특별시 중랑구 망우로 353(상봉동 500) 이노시티 C동 B2F    상봉동
 44    경기도   김포시    김포문화재단                            경기도 김포시 돌문로 26    사우동
 45    경기도   고양시    고양문화재단                       경기도 고양시 덕양구 어울림로 33    성사동
 47    경기도   구리시    구리문화재단                          경기도 구리시 아차산로 453    교문동
 51    경기도   안양시  안양문화예술재단        경기도 안양시 만안구 문예로36번길 16(안양동) 안양아트센터    안양동
 52    경기도   광명시    광명문화재단        경기도 광명시 시청로 20 시민회관 2층 광명문화재단(철산동)    철산동
 53    경기도   부천시    부천문화재단              부천시 원미구 장말로 107 (상동) 복사골문화센터     상동
 56    경기도   용인시    용인문화재단                      경기도 용인시 수지구 포은대로 499    죽전동
 61    경기도   하남시    하남문화재단                           경기도 하남시 신평로 125    덕풍동
 62    경기도   성남시    성남문화재단                      경기도 성남시 분당구 성남대로 808    야탑동
 67  인천광역시   부평구   부평구문화재단                       인천광역시 부평구 아트센터로 166    십정동
 68  인천광역시   연수구    연수문화재단         인천광역시 연수구 비류대로 299(청학동) 청학아트센터 2층    청학동
 69  인천광역시    서구  인천서구문화재단                          인천광역시 서구 서달로 190    가정동
 70  인천광역시    중구  인천중구문화재단                     인천광역시 중구 신포로27번길 83-1  중앙동1가
 71  인천광역시   남동구    남동문화재단       인천광역시 남동구 아암대로1437번길 32(논현동, 소래아트홀)    논현동

       행정동
 4     신설동
 6     신포동
 22   중계본동
 23   돈암2동
 24    사직동
 25    녹번동
 26   행당1동
 27   자양3동
 28   상일1동
 29   None
 30   반포2동
 31   상도4동
 32   신정6동
 33   구로5동
 34   시흥1동
 35    대학동
 36    신당동
 37    대흥동
 38   당산1동
 39    인수동
 40    창5동
 41    제기동
 42    삼전동
 43   상봉1동
 44    사우동
 45   성사2동
 47   교문1동
 51   안양8동
 52   철산3동
 53    상1동
 56   죽전2동
 61   덕풍3동
 62   야탑3동
 67   부평3동
 68    청학동
 69   가정3동
 70    신포동
 71  논현고잔동  }

In [157]:
df_all = pd.concat(munhaw_filtered.values(), ignore_index=True)

In [159]:
df_all.to_csv('data_cleaning/[복지]_문화시설_총합.csv')