In [92]:
import pandas as pd

df = pd.read_excel('인구십만명당문화기반시설수2024.xlsx', names=('행정구역','문화/인구', '문화기반시설수', '주민등록인구'))
df = df[1:]
df.head()

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     행정구역 문화/인구 문화기반시설수   주민등록인구
1   서울특별시   5.1     472  9331828
2  　　　종로구  51.3      71   138336
3   　　　중구  25.7      31   120544
4  　　　용산구   9.3      19   203854
5  　　　성동구   5.5      15   273669

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 1 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   행정구역     233 non-null    object
 1   문화/인구    233 non-null    object
 2   문화기반시설수  233 non-null    object
 3   주민등록인구   233 non-null    object
dtypes: object(4)
memory usage: 7.4+ KB

In [95]:
df['행정구역'] = df['행정구역'].str.strip()
df[df['행정구역']=='종로구'].index

Index([2], dtype='int64')

In [99]:
df_1 = df[78:]
df_2 = df[:78]

In [102]:
si = ['성남시','고양시','부천시','광명시','하남시','남양주시','용인시','김포시','구리시','안양시']
df_1 = df_1[df_1['행정구역'].isin(si)]
df_1

     행정구역 문화/인구 문화기반시설수   주민등록인구
81    성남시   3.4      31   913009
83    안양시   3.1      17   556492
84    부천시   3.9      30   769918
85    광명시   3.6      10   278167
89    고양시   3.8      41  1070120
91    구리시   3.7       7   186882
92   남양주시   3.7      27   732482
97    하남시   3.6      12   329120
98    용인시   4.3      47  1085864
102   김포시   3.5      17   486853

In [106]:
df_total = pd.concat([df_2, df_1], ignore_index=True)
df_total.head()

    행정구역 문화/인구 문화기반시설수   주민등록인구
0  서울특별시   5.1     472  9331828
1    종로구  51.3      71   138336
2     중구  25.7      31   120544
3    용산구   9.3      19   203854
4    성동구   5.5      15   273669

In [111]:
df_total[df_total['행정구역']=='인천광역시'].index

Index([], dtype='int64')

In [ ]:
df_total.drop([0, 51], inplace=True)

In [121]:
df_total.to_csv('ingoo.csv', index=False)