In [1]:
import pandas as pd

data = pd.read_csv('data/경기도_지역아동센터현황.csv', encoding='cp949')
data.head()

,집계일자,시군명,시설명,복지시설전화번호,시설정원(명),소재지우편번호,소재지도로명주소,소재지지번주소,WGS84위도,WGS84경도
0,2024-12-31,가평군,경기도 설악지역아동센터,031-584-9459,19.0,12466.0,경기도 가평군 설악면 탐선길 16,경기도 가평군 설악면 선촌리 443-4번지,37.676165,127.481277
1,2024-12-31,가평군,경기도 또래지역아동센터,031-585-0477,29.0,12437.0,경기도 가평군 조종면 조종새싹로 49,경기도 가평군 조종면 현리 232-3번지,37.822968,127.348548
2,2024-12-31,가평군,경기도 가평지역아동센터,070-7404-2722,40.0,12409.0,경기도 가평군 가평읍 아랫마장길 16,경기도 가평군 가평읍 마장리 747번지,37.843948,127.504126
3,2024-12-31,가평군,경기도 청평지역아동센터,031-584-5963,29.0,12453.0,경기도 가평군 청평면 잠곡로 22,경기도 가평군 청평면 청평리 403-7번지,37.736899,127.421155
4,2024-12-31,고양시,새꿈터지역아동센터,031-911-0611,24.0,10357.0,경기도 고양시 일산동구 산두로 229번길 29,경기도 고양시 일산동구 정발산동 1128번지,37.674761,126.778352

In [2]:
df = data[data['시군명'].isin(['성남시', '고양시', '부천시', '광명시', '하남시', '남양주시', '용인시', '김포시', '구리시', '안양시'])]

In [3]:
df = df[['시군명', '시설명', '소재지도로명주소', '소재지지번주소', 'WGS84위도', 'WGS84경도']]

In [5]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}
params = {"query": "경기도 고양시 덕양구 토당로 78번길 7 22 2층"}

def get_address(address):
    try:
        params = {'query' : address}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()
        lat = a['documents'][0]['y']   # 위도
        lon = a['documents'][0]['x']   # 경도
        return pd.Series([lat, lon])
        
    except Exception as e:
        print(f"주소 변환 실패: {address} / 에러: {e}")
        return pd.Series([None, None])


df.loc[df['WGS84위도'].isna(),  ['WGS84위도', 'WGS84경도']] = df.loc[df['WGS84위도'].isna(), '소재지도로명주소'].apply(get_address).values
# print(df.loc[df['WGS84위도'].isna(), '소재지도로명주소'].apply(get_address).values)

주소 변환 실패: 경기도 구리시 아치울길23번길 23 9 / 에러: list index out of range
주소 변환 실패: 경기도 부천시 오정구 상오정로 611 / 에러: list index out of range

C:\Users\asia\AppData\Local\Temp\ipykernel_23168\3277224621.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['37.6232100397986', '37.6641093574766', '37.6723569605531', '37.685667841824', '37.622727298176', '37.6513337997741', '37.6068601849762', '37.5967081269633', None, '37.6015329224476', '37.6487159185073', '37.6880874870531', '37.7190234415702', '37.6640468493905', '37.6508992015602', '37.6252400112841', '37.7262963569465', '37.6818297195999', '37.6555660149867', '37.6101394706731', '37.6580361473932', '37.661563508927', '37.6396437799551', '37.5784434334679', '37.7220906598685', '37.6556501634144', '37.6848002963687', '37.6364791062323', '37.6590750979971', '37.6570638839299', '37.7262963569465', '37.7153642032038', '37.7113534940093', '37.6557922110201', '37.5181565987101', '37.4744934342893', '37.4785310581576', '37.518826178145', '37.5277313685765', None, '37.494381794664', '37.4798841909054', '37.4386463861231', '37.4124541371308', '37.1927021072829', '37.2727148005715', '37.3314168796303', '37.272719159393', '37.1985924978014']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['WGS84위도'].isna(),  ['WGS84위도', 'WGS84경도']] = df.loc[df['WGS84위도'].isna(), '소재지도로명주소'].apply(get_address).values
C:\Users\asia\AppData\Local\Temp\ipykernel_23168\3277224621.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['126.819300489173', '126.797295086599', '126.748088762016', '126.71918344569', '126.843997452758', '126.833310726631', '127.129400350625', '127.132783463957', None, '127.146859656075', '126.659314210829', '126.604952180894', '126.637128400292', '126.63833474662', '127.303623912292', '127.201529169508', '127.194573735477', '127.210918342848', '127.299992724586', '127.154665198386', '127.272241251617', '127.347664312633', '127.283982426922', '127.224030754479', '127.200310268591', '127.344764749913', '127.312274602449', '127.21279983985', '127.29105773317', '127.302360486271', '127.194573735477', '127.179255757671', '127.195544004984', '127.272144438221', '126.795044523081', '126.798025361921', '126.778289882901', '126.787774418557', '126.787655972023', None, '126.793068738204', '126.810382800447', '127.165741680085', '126.912175938297', '127.21114268519', '127.073629336592', '127.100743062181', '127.107306937053', '127.208474244726']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['WGS84위도'].isna(),  ['WGS84위도', 'WGS84경도']] = df.loc[df['WGS84위도'].isna(), '소재지도로명주소'].apply(get_address).values

In [6]:
df

,시군명,시설명,소재지도로명주소,소재지지번주소,WGS84위도,WGS84경도
4,고양시,새꿈터지역아동센터,경기도 고양시 일산동구 산두로 229번길 29,경기도 고양시 일산동구 정발산동 1128번지,37.674761,126.778352
5,고양시,맑은샘지역아동센터,경기도 고양시 일산동구 고봉로 658번길 13,경기도 고양시 일산동구 성석동 1082-27번지,37.715616,126.789983
6,고양시,한빛지역아동센터,경기도 고양시 덕양구 행당로 11번길 11 5층,경기도 고양시 덕양구 토당동 876-7번지 5층,37.620404,126.82596
7,고양시,푸른학교반디교실지역아동센터,경기도 고양시 덕양구 토당로 78번길 7 22 2층,NaN,37.6232100397986,126.819300489173
8,고양시,신성지역아동센터,경기도 고양시 일산동구 일산로 11,경기도 고양시 일산동구 백석동 1344번지 흰돌마을5단지아파트,37.64144,126.784387
...,...,...,...,...,...,...
737,하남시,민들레꽃피우기지역아동센터,경기도 하남시 하남대로784번안길6 202호,경기도 하남시 신장동 387-1번지 202호,37.540684,127.211553
738,하남시,LH행복꿈터미사강변지역아동센터,경기도 하남시 아리수로 565 3 관리사무소 2층,경기도 하남시 망월동 949번지 미사강변도시13단지 3 관리사무소 2층,37.567994,127.189956
739,하남시,온누리지역아동센터,경기도 하남시 덕풍로 65번길 6 2층,경기도 하남시 덕풍동 226-19번지 2층,37.551099,127.206023
740,하남시,한마음지역아동센터,경기도 하남시 신장로184번길 24 2층,경기도 하남시 덕풍동 386번지 2층,37.541866,127.201225
741,하남시,푸른초장지역아동센터,경기도 하남시 미사강변대로80 그린프라자 403호,경기도 하남시 풍산동 504-2번지 그린프라자 403호,37.557046,127.18785

In [ ]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/geo/coord2address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_dong(xy):
    x = xy['WGS84경도']
    y = xy['WGS84위도']
    try:
        params = {'x' : x, 'y' : y}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()

        lat = a['documents'][0]['address']['region_3depth_name']
        return lat

    except Exception as e:
        print(f"주소 변환 실패: {xy} / 에러: {e}")
        return None


df['행정동'] = df[['WGS84경도', 'WGS84위도']].apply(get_dong, axis=1)

C:\Users\asia\AppData\Local\Temp\ipykernel_3512\4226366312.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['행정동'] = df[['WGS84경도', 'WGS84위도']].apply(get_dong, axis=1)

In [94]:
df.to_csv('data_cleaning/경기도_지역아동센터현황_동추가.csv')

In [6]:
data = pd.read_csv('data/서울시 지역아동센터 시설현황정보.csv', encoding='cp949')

In [18]:
data = data[['시설명', '자치구명', 'X좌표값', 'Y좌표값', '기본주소', '상세주소']]
data.head()

           시설명  자치구명        X좌표값       Y좌표값                  기본주소      상세주소
0  고척재미난지역아동센터   구로구         NaN        NaN                   NaN       NaN
1     진성지역아동센터   광진구  127.086920  37.567220  서울특별시 광진구 용마산로26길 10   제 (중곡동)
2     한울지역아동센터  영등포구         NaN        NaN   서울 영등포구 가마산로46가길 10       NaN
3    테스트지역아동센터   강남구  126.977675  37.566477     서울특별시 중구 세종대로 110   (태평로1가)
4    봄이랑지역아동센터   중랑구         NaN        NaN  서울 중랑구 봉우재로58길 16 3층       NaN

In [29]:
data[data['기본주소'].isna()]

Empty DataFrame
Columns: [시설명, 자치구명, X좌표값, Y좌표값, 기본주소, 상세주소]
Index: []

In [26]:
data.loc[data['시설명'] == '열린지역아동센터', '기본주소'] = '서울 마포구 월드컵북로48길 8 (상암동, 2층)'

In [ ]:
data = data.dropna(subset=['기본주소'])

In [42]:
data.head()

,시설명,자치구명,X좌표값,Y좌표값,기본주소,상세주소,행정동
1,진성지역아동센터,광진구,127.08692,37.56722,서울특별시 광진구 용마산로26길 10,제 (중곡동),중곡동
2,한울지역아동센터,영등포구,126.899625430464,37.5011580959347,서울 영등포구 가마산로46가길 10,NaN,None
3,테스트지역아동센터,강남구,126.977675,37.566477,서울특별시 중구 세종대로 110,(태평로1가),태평로1가
4,봄이랑지역아동센터,중랑구,127.095309007608,37.5937889058086,서울 중랑구 봉우재로58길 16 3층,NaN,None
5,라이프칠드런지역아동센터,구로구,126.82167358851,37.4841083960883,서울 구로구 연동로13길 7 2층,NaN,None

In [41]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_address(address):
    try:
        params = {'query' : address}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()
        lat = a['documents'][0]['y']   # 위도
        lon = a['documents'][0]['x']   # 경도
        return pd.Series([lat, lon])
        
    except Exception as e:
        print(f"주소 변환 실패: {address} / 에러: {e}")
        return pd.Series([None, None])

li = [2,4,5,6,7,8]
data.loc[li,  ['Y좌표값', 'X좌표값']] = data.loc[li,  '기본주소'].apply(get_address).values

In [35]:
data.loc[data['X좌표값'].isna(),  ['X좌표값', 'Y좌표값']]

   X좌표값  Y좌표값
2   NaN   NaN
4   NaN   NaN
5   NaN   NaN
6   NaN   NaN
7   NaN   NaN
8   NaN   NaN

In [44]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/geo/coord2address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_dong(xy):
    x = xy['X좌표값']
    y = xy['Y좌표값']
    try:
        params = {'x' : x, 'y' : y}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()

        lat = a['documents'][0]['address']['region_3depth_name']
        return lat

    except Exception as e:
        print(f"주소 변환 실패: {xy} / 에러: {e}")
        return None


data.loc[li, '행정동'] = data.loc[li, ['X좌표값', 'Y좌표값']].apply(get_dong, axis=1)

In [46]:
data.to_csv('data_cleaning/서울시_지역아동센터_ 동추가.csv')

In [51]:
df_in = pd.read_csv('data/인천광역시_지역아동센터현황_2025.csv', encoding='cp949')
df_in.head()

,연번,군구명,시설명,주소,전화번호,아동정원,종사자,운영주체
0,1,중구,구립 연안지역아동센터,"인천광역시 축항대로86번길 38, 3층(항동7가)",032-881-9790,29,3,재단법인 성산청소년효재단
1,2,중구,구립 월디지역아동센터,"인천광역시 참외전로72번길 25, 3층(전동)",032-773-0984,49,4,대한성공회유지재단
2,3,중구,그루터기지역아동센터,"인천광역시 참외전로 13번길 2, 송월아파트상가 제121-1호",032-761-0964,40,4,개인
3,4,동구,금창지역아동센터,인천광역시 금곡로 44(금창동),032-777-8991,25,3,개인
4,5,동구,모리아지역아동센터,인천광역시 화수로 3-7,032-772-7142,19,2,개인

In [63]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_address(address):
    try:
        params = {'query' : address}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()
        lat = a['documents'][0]['y']   # 위도
        lon = a['documents'][0]['x']   # 경도
        return pd.Series([lat, lon])
        
    except Exception as e:
        print(f"주소 변환 실패: {address} / 에러: {e}")
        return pd.Series([None, None])

df_in[['Y좌표값', 'X좌표값']] = df_in['주소'].apply(get_address).values

주소 변환 실패: 인천광역시 봉오대로698번길 11, 2~3층(작전동) / 에러: list index out of range
주소 변환 실패: 인천광역시 안남로573번길 26, 401~404호(효성동) / 에러: list index out of range
주소 변환 실패: 인천광역시 장제로 997번길2, 2~3층(박촌동) / 에러: list index out of range

In [70]:
df_in[df_in['X좌표값'].isna()]

Empty DataFrame
Columns: [연번, 군구명, 시설명, 주소, 전화번호, 아동정원, 종사자, 운영주체, Y좌표값, X좌표값]
Index: []

In [69]:
df_in.loc[df_in['시설명']=='소양지역아동센터', ['Y좌표값', 'X좌표값']] = ['37.5547074937728' ,'126.745150027349']

      "x": "126.745150027349",
      "y": "37.5547074937728"

In [71]:
df_in = df_in[['군구명','시설명', '주소','X좌표값', 'Y좌표값']]

In [75]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/geo/coord2address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_dong(xy):
    x = xy['X좌표값']
    y = xy['Y좌표값']
    try:
        params = {'x' : x, 'y' : y}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()

        lat = a['documents'][0]['address']['region_3depth_name']
        return lat

    except Exception as e:
        print(f"주소 변환 실패: {xy} / 에러: {e}")
        return None


df_in['행정동'] = df_in[['X좌표값', 'Y좌표값']].apply(get_dong, axis=1)

C:\Users\asia\AppData\Local\Temp\ipykernel_12592\3855073930.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_in['행정동'] = df_in[['X좌표값', 'Y좌표값']].apply(get_dong, axis=1)

In [76]:
df_in

,군구명,시설명,주소,X좌표값,Y좌표값,행정동
0,중구,구립 연안지역아동센터,"인천광역시 축항대로86번길 38, 3층(항동7가)",126.604637717683,37.4535561929881,항동7가
1,중구,구립 월디지역아동센터,"인천광역시 참외전로72번길 25, 3층(전동)",126.628948176283,37.4768252149958,전동
2,중구,그루터기지역아동센터,"인천광역시 참외전로 13번길 2, 송월아파트상가 제121-1호",126.621251106219,37.4800306228344,송월동1가
3,동구,금창지역아동센터,인천광역시 금곡로 44(금창동),126.640496741799,37.4733605115552,금곡동
4,동구,모리아지역아동센터,인천광역시 화수로 3-7,126.636118678833,37.4799164272448,송현동
...,...,...,...,...,...,...
170,강화군,화도마리지역아동센터,인천광역시 화도면 가능포로 37-12(상방리),126.417742307688,37.6359527985513,화도면 상방리
171,강화군,희망터지역아동센터,인천광역시 길상면 온수길38번길 14(온수리),126.48970275388,37.6405179610665,길상면 온수리
172,강화군,강화지역아동센터,"인천광역시 강화읍 갑룡길117번길 28-3, 나동 102호(용정리)",126.50503589828,37.747141028234,강화읍 용정리
173,옹진군,영흥지역아동센터,인천광역시 영흥면 영흥서로 220,126.478675628857,37.2740263952325,영흥면 내리
174,서구,서구공립지역아동센터,인천광역시 율도로 16번길 18(석남동),126.662657314166,37.5123707259997,석남동

In [78]:
df_in.to_csv('data_cleaning/인천_지역아동센터_동추가.csv')