In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('data_dong/[공통] 전체_인구통계_정제완료.xlsx')
df_adong = pd.read_csv('data_dong/[복지]통합지역아동센터_최종.csv')
df_munhwa = pd.read_csv('data_dong/[복지]_문화시설_총합_최종.csv')
df = df.rename(columns={'읍면동명':'행정동'})
df

,시도명,시군구명,행정동,남자,여자,0세남자,1세남자,2세남자,3세남자,4세남자,...,101세여자,102세여자,103세여자,104세여자,105세여자,106세여자,107세여자,108세여자,109세여자,110세이상 여자
0,서울특별시,종로구,청운효자동,4895,5919,17,21,21,20,20,...,0,0,0,0,0,0,0,0,0,0
1,서울특별시,종로구,사직동,3921,4986,6,19,11,21,22,...,0,1,0,0,0,0,0,0,0,0
2,서울특별시,종로구,삼청동,996,1103,5,3,1,3,4,...,0,0,0,0,0,0,0,0,0,0
3,서울특별시,종로구,부암동,4154,4750,15,16,14,15,12,...,1,0,1,0,0,0,0,0,0,0
4,서울특별시,종로구,평창동,7827,9147,36,37,42,26,51,...,3,2,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,경기도,김포시,풍무동,28853,30819,168,173,195,213,231,...,0,0,0,1,0,0,0,0,0,0
859,경기도,김포시,장기동,19695,20571,106,98,131,139,178,...,1,0,0,0,0,0,0,0,0,0
860,경기도,김포시,구래동,22797,22833,169,165,168,196,177,...,0,0,1,0,1,0,0,0,0,0
861,경기도,김포시,마산동,17458,17999,153,153,149,184,207,...,1,0,0,0,0,0,0,0,0,0
862,경기도,김포시,운양동,23758,24998,135,148,142,210,203,...,2,0,0,0,0,0,0,0,0,0

In [36]:
df=df.rename(columns={'시군구명':'시군구'})

In [21]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_address(address):
    try:
        params = {'query' : address}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()
        sigungoo = a['documents'][0]['address']['region_2depth_name']   # 시군구
        # law_dong = a['documents'][0]['address']['region_3depth_name']   # 법정동
        # hang_dong = a['documents'][0]['address']['region_3depth_h_name']   # 행정동
        return sigungoo
        
    except Exception as e:
        print(f"주소 변환 실패: {address} / 에러: {e}")
        return pd.Series([None, None])

In [29]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/geo/coord2address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_dong(xy):
    x = xy['X좌표값']
    y = xy['Y좌표값']
    try:
        params = {'x' : x, 'y' : y}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()

        sigungoo = a['documents'][0]['address']['region_2depth_name']
        return sigungoo

    except Exception as e:
        print(f"주소 변환 실패: {xy} / 에러: {e}")
        return None

In [30]:
df_adong['시군구'] = df_adong.apply(get_dong, axis=1)

In [32]:
df_adong[df_adong['시군구'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, 시설명, 주소, Y좌표값, X좌표값, 행정동, 법정동, 시군구]
Index: []

In [4]:
df_munhwa.head()

,Unnamed: 0,시도,시군구,이름,주소,법정동,행정동
0,0,서울,서초구,국립중앙도서관,서울특별시 서초구 반포대로 201 (반포동),반포동,반포4동
1,1,서울,영등포구,국회도서관,서울특별시 영등포구 의사당대로 1 (여의도동),여의도동,여의동
2,2,서울,서초구,국립장애인도서관,서울특별시 서초구 반포대로 201 (반포동),반포동,반포4동
3,3,경기,고양시,법원도서관,경기도 고양시 일산동구 호수로 550 (장항동),장항동,장항2동
4,4,서울,강남구,서울특별시교육청강남도서관,서울특별시 강남구 선릉로116길 45 (삼성동) 서울특별시교육청강남도서관,삼성동,삼성2동

In [39]:
df_adong

,Unnamed: 0,시설명,주소,Y좌표값,X좌표값,행정동,법정동,시군구
0,0,새꿈터지역아동센터,경기도 고양시 일산동구 산두로 229번길 29,37.674761,126.778352,정발산동,정발산동,고양시 일산동구
1,1,맑은샘지역아동센터,경기도 고양시 일산동구 고봉로 658번길 13,37.715616,126.789983,고봉동,성석동,고양시 일산동구
2,2,한빛지역아동센터,경기도 고양시 덕양구 행당로 11번길 11 5층,37.620404,126.825960,행주동,토당동,고양시 덕양구
3,3,푸른학교반디교실지역아동센터,경기도 고양시 덕양구 토당로 78번길 7 22 2층,37.623210,126.819300,능곡동,토당동,고양시 덕양구
4,4,신성지역아동센터,경기도 고양시 일산동구 일산로 11,37.641440,126.784387,백석2동,백석동,고양시 일산동구
...,...,...,...,...,...,...,...,...
895,896,화도마리지역아동센터,인천광역시 화도면 가능포로 37-12(상방리),37.635953,126.417742,화도면,화도면 상방리,강화군
896,897,희망터지역아동센터,인천광역시 길상면 온수길38번길 14(온수리),37.640518,126.489703,길상면,길상면 온수리,강화군
897,898,강화지역아동센터,"인천광역시 강화읍 갑룡길117번길 28-3, 나동 102호(용정리)",37.747141,126.505036,강화읍,강화읍 용정리,강화군
898,899,영흥지역아동센터,인천광역시 영흥면 영흥서로 220,37.274026,126.478676,영흥면,영흥면 내리,옹진군
899,900,서구공립지역아동센터,인천광역시 율도로 16번길 18(석남동),37.512371,126.662657,석남1동,석남동,서구

In [33]:
df_adong.groupby('행정동').count()

      Unnamed: 0  시설명  주소  Y좌표값  X좌표값  법정동  시군구
행정동
가리봉동           1    1   1     1     1    1    1
가산동            1    1   1     1     1    1    1
가정1동           1    1   1     1     1    1    1
가좌1동           3    3   3     3     3    3    3
가좌2동           2    2   2     2     2    2    2
...          ...  ...  ..   ...   ...  ...  ...
효성2동           5    5   5     5     5    5    5
효창동            1    1   1     1     1    1    1
후암동            1    1   1     1     1    1    1
휘경2동           2    2   2     2     2    2    2
흑석동            4    4   4     4     4    4    4

[494 rows x 7 columns]

In [34]:
df.groupby('행정동')['시군구명'].nunique().sort_values(ascending=False)

행정동
신촌동     3
위례동     3
중앙동     3
논현1동    2
논현2동    2
       ..
후암동     1
휘경1동    1
휘경2동    1
흑석동     1
흥도동     1
Name: 시군구명, Length: 851, dtype: int64

In [44]:
df_adong2 = df_adong.groupby(['행정동', '시군구']).size()

In [43]:
df_adong.groupby(['행정동', '시군구']).size()

행정동   시군구
가리봉동  구로구     1
가산동   금천구     1
가정1동  서구      1
가좌1동  서구      3
가좌2동  서구      2
             ..
효성2동  계양구     5
효창동   용산구     1
후암동   용산구     1
휘경2동  동대문구    2
흑석동   동작구     4
Length: 499, dtype: int64

In [42]:
len(set(df['행정동']) & set(df_adong['행정동']))

494

In [45]:
df_fac = df_adong2.reset_index(name='시설수')

In [46]:
df_merge = df_fac.merge(df, on=['시군구', '행정동'], how='left')

In [65]:
df_merge.columns.get_loc('0세여자')

117

In [ ]:
df_merge.iloc[:, 117:136].sum(axis=1)

0       155.0
1       490.0
2      4025.0
3       519.0
4      1016.0
        ...
494    1637.0
495     604.0
496     708.0
497    1170.0
498    2033.0
Length: 499, dtype: float64

In [77]:
df_merge2=df_merge[df_merge.columns[:25].to_list() + df_merge.columns[117:136].to_list()]

In [79]:
df_merge2.drop(columns=(['남자', '여자']), inplace=True)

C:\Users\asia\AppData\Local\Temp\ipykernel_21256\1243099113.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge2.drop(columns=(['남자', '여자']), inplace=True)

In [93]:
df_merge2['합계']=df_merge2.iloc[:,4:23].sum(axis=1) + df_merge2.iloc[:,23:].sum(axis=1)

C:\Users\asia\AppData\Local\Temp\ipykernel_21256\2492898870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge2['합계']=df_merge2.iloc[:,4:23].sum(axis=1) + df_merge2.iloc[:,23:].sum(axis=1)

In [62]:
df_merge2=df_merge2.drop(columns=(['남자','여자']))

In [141]:
df_merge2['센터지수(정규화전)'] = (df_merge2['시설수']/df_merge2['합계']) *1000

C:\Users\asia\AppData\Local\Temp\ipykernel_21256\2943187793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge2['센터지수(정규화전)'] = (df_merge2['시설수']/df_merge2['합계']) *1000

In [ ]:
df_merge2= df_merge2.dropna(subset=['0세남자'])

,행정동,시군구,시설수,시도명,0세남자,1세남자,2세남자,3세남자,4세남자,5세남자,...,12세여자,13세여자,14세여자,15세여자,16세여자,17세여자,18세여자,합계,센터지수(정규화전),센터지수(정규화후)
0,가리봉동,구로구,1,서울특별시,17.0,9.0,10.0,3.0,9.0,7.0,...,10.0,6.0,8.0,13.0,11.0,7.0,13.0,349.0,2.865330,0.0
1,가산동,금천구,1,서울특별시,52.0,35.0,31.0,23.0,25.0,27.0,...,23.0,25.0,26.0,18.0,29.0,28.0,32.0,1003.0,0.997009,0.0
2,가정1동,서구,1,인천광역시,172.0,180.0,170.0,200.0,210.0,224.0,...,231.0,240.0,228.0,155.0,172.0,154.0,165.0,8260.0,0.121065,0.0
3,가좌1동,서구,3,인천광역시,40.0,43.0,29.0,27.0,22.0,23.0,...,24.0,25.0,30.0,33.0,22.0,38.0,42.0,1134.0,2.645503,0.0
4,가좌2동,서구,2,인천광역시,49.0,51.0,33.0,39.0,32.0,48.0,...,62.0,69.0,78.0,78.0,78.0,86.0,83.0,2142.0,0.933707,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,효성2동,계양구,5,인천광역시,65.0,53.0,52.0,64.0,57.0,55.0,...,109.0,119.0,115.0,133.0,108.0,118.0,143.0,3280.0,1.524390,0.0
495,효창동,용산구,1,서울특별시,47.0,28.0,31.0,18.0,28.0,32.0,...,27.0,22.0,32.0,31.0,33.0,30.0,42.0,1206.0,0.829187,0.0
496,후암동,용산구,1,서울특별시,28.0,23.0,23.0,26.0,23.0,25.0,...,48.0,54.0,43.0,45.0,37.0,48.0,71.0,1508.0,0.663130,0.0
497,휘경2동,동대문구,2,서울특별시,55.0,30.0,41.0,36.0,38.0,36.0,...,75.0,85.0,79.0,77.0,95.0,94.0,134.0,2304.0,0.868056,0.0
498,흑석동,동작구,4,서울특별시,101.0,82.0,102.0,100.0,81.0,101.0,...,107.0,124.0,109.0,94.0,91.0,93.0,104.0,4093.0,0.977278,0.0

In [117]:
max_center = df_merge2['센터지수(정규화전)'].max()
min_center = df_merge2['센터지수(정규화전)'].min()
df_merge2['센터지수(정규화후)'] = (df_merge2['센터지수(정규화전)'] - min_center) / (max_center - min_center)

C:\Users\asia\AppData\Local\Temp\ipykernel_21256\3546172665.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge2['센터지수(정규화후)'] = (df_merge2['센터지수(정규화전)'] - min_center) / (max_center - min_center)

In [119]:
df_merge2['가중치 적용'] = df_merge2['센터지수(정규화후)'] * 0.0804

C:\Users\asia\AppData\Local\Temp\ipykernel_21256\671098393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge2['가중치 적용'] = df_merge2['센터지수(정규화후)'] * 0.0804

In [121]:
max_center = df_merge2['가중치 적용'].max()
min_center = df_merge2['가중치 적용'].min()
df_merge2['최종'] = ((df_merge2['가중치 적용'] - min_center) / (max_center - min_center)) * 100

C:\Users\asia\AppData\Local\Temp\ipykernel_21256\3078759367.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge2['최종'] = ((df_merge2['가중치 적용'] - min_center) / (max_center - min_center)) * 100

In [123]:
df_merge2.to_csv('final/[복지]지역아동센터_동별지수.csv')

In [127]:
df_munhwa2 = df_munhwa.groupby(['행정동', '시군구']).size()

In [128]:
df_munhwa2 = df_adong2.reset_index(name='시설수')

In [131]:
df_mun_merge = df_munhwa2.merge(df, on=['시군구', '행정동'], how='left')

In [135]:
df_mun_merge = df_mun_merge.iloc[:, :6]

In [137]:
df_mun_merge['합계'] = df_mun_merge['남자'] + df_mun_merge['여자']

In [139]:
df_mun_merge = df_mun_merge.drop(columns=(['남자', '여자']))

In [143]:
df_mun_merge['지수'] = (df_mun_merge['시설수']/df_mun_merge['합계'])*1000

In [145]:
max_center = df_mun_merge['지수'].max()
min_center = df_mun_merge['지수'].min()
df_mun_merge['지수(정규화후)'] = (df_mun_merge['지수'] - min_center) / (max_center - min_center)

In [ ]:
df_mun_merge['가중치']=df_mun_merge['지수(정규화후)'] * 0.0442

In [149]:
max_center = df_mun_merge['가중치'].max()
min_center = df_mun_merge['가중치'].min()
df_mun_merge['최종'] = ((df_mun_merge['가중치'] - min_center) / (max_center - min_center)) * 100

In [151]:
df_mun_merge.to_csv('final/[복지]문화시설_동별지수.csv')